class BreedPresets {
  static const List<String> defaultBreeds = [
    'Airedale Terrier',
    'Akita',
    'Alaskan Malamute',
    'American Staffordshire Terrier',
    'Australian Shepherd',
    'Australian Cattle Dog',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Belgian Malinois',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Boxer',
    'Bull Terrier',
    'Bulldog (English)',
    'Bulldog (French)',
    'Bullmastiff',
    'Cairn Terrier',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Chinese Shar-Pei',
    'Cocker Spaniel (American)',
    'Cocker Spaniel (English)',
    'Collie',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'Dogue de Bordeaux',
    'English Setter',
    'English Springer Spaniel',
    'English Toy Spaniel',
    'Eurasier',
    'Finnish Spitz',
    'Fox Terrier (Smooth)',
    'Fox Terrier (Wire)',
    'German Shepherd',
    'German Shorthaired Pointer',
    'German Wirehaired Pointer',
    'Golden Retriever',
    'Gordon Setter',
    'Great Dane',
    'Great Pyrenees',
    'Greyhound',
    'Havanese',
    'Irish Setter',
    'Irish Terrier',
    'Irish Wolfhound',
    'Italian Greyhound',
    'Jack Russell Terrier',
    'Japanese Chin',
    'Keeshond',
    'Labrador Retriever',
    'Lakeland Terrier',
    'Lhasa Apso',
    'Maltese',
    'Mastiff',
    'Miniature Schnauzer',
    'Newfoundland',
    'Norfolk Terrier',
    'Norwegian Elkhound',
    'Norwich Terrier',
    'Old English Sheepdog',
    'Papillon',
    'Pekingese',
    'Pembroke Welsh Corgi',
    'Pharaoh Hound',
    'Pointer',
    'Pomeranian',
    'Poodle (Miniature)',
    'Poodle (Standard)',
    'Poodle (Toy)',
    'Portuguese Water Dog',
    'Pug',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Saint Bernard',
    'Saluki',
    'Samoyed',
    'Schipperke',
    'Schnauzer (Standard)',
    'Schnauzer (Miniature)',
    'Scottish Terrier',
    'Shetland Sheepdog',
    'Shiba Inu',
    'Shih Tzu',
    'Siberian Husky',
    'Silky Terrier',
    'Skye Terrier',
    'Staffordshire Bull Terrier',
    'Sussex Spaniel',
    'Thai Ridgeback',
    'Tibetan Spaniel',
    'Tibetan Terrier',
    'Vizsla',
    'Weimaraner',
    'Welsh Springer Spaniel',
    'Welsh Terrier',
    'West Highland White Terrier',
    'Whippet',
    'Yorkshire Terrier',
  ];

  static List<String> search(String query) {
    if (query.isEmpty) return defaultBreeds;
    final lower = query.toLowerCase();
    return defaultBreeds.where((b) => b.toLowerCase().contains(lower)).toList();
  }
}